Code/MachineManagement/Controllers/HomeController.cs
using DatabaseObject.Domain;
using DatabaseObject.Manager;
using DatabaseObject.Util;
using MachineManagement.App_Start;
using MachineManagement.Models;
using System;
using System.Web.Mvc;

namespace MachineManagement.Controllers
{
    public class HomeController : BaseController
    {
        private UserManager userManager = new UserManager();

        public ActionResult Login()
        {
            Session.Clear();

            return View();
        }

        public ActionResult Menu()
        {
            if (CheckSession() == false)
            {
                Response.Redirect(Url.Action(ConstDefinition.HOME_ACTION, ConstDefinition.HOME_CONTROLLER), true);
                return null;
            }

            return View();
        }

        [HttpPost]
        public JsonResult Login(string loginID, string loginPwd)
        {
            ResultModel result = new ResultModel();

            try
            {
                Session.Clear();

                UserInfo existingInfo = this.userManager.GetUser(loginID);

                if (existingInfo == null)
                    result.SetFailed("The login account has not registered or has deleted");
                else if (existingInfo.LoginPwd != SQLUtil.TrimNull(loginPwd))
                    result.SetFailed("The password is incorrect");
                else
                {
                    existingInfo.LoginPwd = null;
                    SaveSession(existingInfo);
                }
            }
            catch (Exception ex)
            {
                result.SetFailed(ex.Message);
            }

            return JsonResult(result);
        }
        
    }
}

Code/MachineManagement/Controllers/MachineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MachineManagement.Controllers
{
    public class MachineController : Controller
    {
        // GET: Machine
        public ActionResult MachineList()
        {
            return View();
        }
    }
}

Code/MachineManagement/Controllers/UserController.cs
using DatabaseObject.Domain;
using DatabaseObject.Manager;
using MachineManagement.App_Start;
using MachineManagement.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MachineManagement.Controllers
{
    public class UserController : BaseController
    {
        private UserManager userManager = new UserManager();

        public ActionResult UserList()
        {
            return View();
        }

        public JsonResult QueryUserList(string filterField, string filterText, int currentPage)
        {
            if (CheckSession() == false)
            {
                return Json(new SessionTimeoutModel(), JsonRequestBehavior.AllowGet);
            }

            ResultModel result = new ResultModel();
            try
            {
                int totalRecord = this.userManager.QueryUsersCount(filterField, filterText);
                int pageSize = ConstDefinition.PAGE_SIZE;
                result.SetTotalPages(totalRecord, pageSize);

                List<UserInfo> infos = this.userManager.QueryUsers(filterField, filterText, result.GetCurRowNum(currentPage, pageSize), pageSize);
                result.JsonObject = JsonConvert.SerializeObject(infos, new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore });
            }
            catch (Exception ex)
            {
                result.SetFailed(ex.Message);
            }
            return JsonResult(result);
        }

        public JsonResult GetUser(int id)
        {
            if (CheckSession() == false)
            {
                return Json(new SessionTimeoutModel(), JsonRequestBehavior.AllowGet);
            }

            ResultModel result = new ResultModel();
            try
            {
                UserInfo info = this.userManager.GetUser(id);
                result.JsonObject = JsonConvert.SerializeObject(info, new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore });
            }
            catch (Exception ex)
            {
                result.SetFailed(ex.Message);
            }
            return JsonResult(result);
        }

        [HttpPost]
        public JsonResult SaveUser(UserInfo info)
        {
            if (CheckSession() == false)
            {
                return Json(new SessionTimeoutModel(), JsonRequestBehavior.AllowGet);
            }

            ResultModel result = new ResultModel();
            try
            {
                if (info.ID == 0)
                {
                    UserInfo newInfo = this.userManager.AddUser(info);
                    result.JsonObject = JsonConvert.SerializeObject(newInfo, new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore });
                }
                else
                {
                    this.userManager.UpdateUser(info);
                }
            }
            catch (Exception ex)
            {
                result.SetFailed(ex.Message);
            }
            return JsonResult(result);
        }

        [HttpPost]
        public JsonResult UpdatePassword(int id, string loginPwd)
        {
            if (CheckSession() == false)
            {
                return Json(new SessionTimeoutModel(), JsonRequestBehavior.AllowGet);
            }

            ResultModel result = new ResultModel();
            try
            {
               this.userManager.UpdatePassword(id, loginPwd);
            }
            catch (Exception ex)
            {
                result.SetFailed(ex.Message);
            }
            return JsonResult(result);
        }

        [HttpPost]
        public JsonResult DeleteUser(int id)
        {
            if (CheckSession() == false)
            {
                return Json(new SessionTimeoutModel(), JsonRequestBehavior.AllowGet);
            }

            ResultModel result = new ResultModel();
            try
            {
                bool isAdmin = ((UserInfo)Session[SESSION_USER]).IsAdmin;
                if(isAdmin)
                    this.userManager.DeleteUser(id);
                else
                    result.SetFailed("You do not have this permission, please notify the administrator");
            }
            catch (Exception ex)
            {
                result.SetFailed(ex.Message);
            }
            return JsonResult(result);
        }

        public JsonResult CheckUserLoginID(int id, string loginID)
        {
            if (CheckSession() == false)
            {
                return Json(new SessionTimeoutModel(), JsonRequestBehavior.AllowGet);
            }

            ResultModel result = new ResultModel();
            try
            {
                bool existed = this.userManager.CheckUserLoginID(id, loginID);

                if (existed == false)
                    result.JsonObject = "0";
                else
                    result.JsonObject = "1";
            }
            catch (Exception ex)
            {
                result.SetFailed(ex.Message);
            }
            return JsonResult(result);
        }
    }
}

Code/MachineManagement/Views/Home/Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@Html.Raw(DatabaseObject.Domain.Constants.SYSTEM_NAME)</title>
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" />
    <script src="~/Content/Scripts/jquery-1.11.0.js"></script>
    <script src="~/Content/scripts/common.js"></script>
</head>
<body>
    <!--header-->
    <header class="loginHeaderBar">
        <span class="headerTitle"><b>@Html.Raw(DatabaseObject.Domain.Constants.SYSTEM_NAME)</b></span>
    </header>
    <div class="mainFrame">
        <div class="loginContent">
            <table class="loginInfo" width="300" align="center" cellpadding="6" cellspacing="10" style="margin: 0 auto;">
                <tr><td><span>Login Please</span></td></tr>
                <tr><td></td></tr>
                <tr><td></td></tr>
                <tr>
                    <td>
                        <input type="text" class="loginEntryUser" id="loginEmail" placeholder="please enter your account" value="" />
                    </td>
                </tr>
                <tr><td></td></tr>
                <tr>
                    <td>
                        <input type="password" class="loginEntryPwd" id="loginPwd" placeholder="Please enter your password" />
                    </td>
                </tr>
                <tr><td><label class="required" id="reqErrorMsg"></label></td></tr>
                <tr><td></td></tr>
                <tr><td></td></tr>
                <tr>
                    <td align="center">
                        <button type="button" class="loginButton" id="btnLogin" />Login
                    </td>
                </tr>
            </table>
        </div>
    </div>
    @*footer*@
    <footer>
        <table style="width:inherit;">
            <tr>
                <td style="text-align:center; white-space:nowrap;">@Html.Raw(DatabaseObject.Domain.Constants.SYSTEM_NAME)</td>
            </tr>
        </table>
    </footer>
</body>
</html>
<script type="text/javascript">
    $().ready(function () {
        CenterizePage();
    });

    $(window).resize(function () {
        CenterizePage();
    });

    function CenterizePage() {
        var divHeight = $(".loginContent").height();
        var clientHeight = $(this).height();

        $(".loginContent").css("margin-top", (clientHeight - divHeight) / 2 + "px");
    }

    $("#btnLogin").click(function () {
        $("#reqErrorMsg").html("");

        var loginEmail = $.trim($("#loginEmail").val());
        if (loginEmail == "") {
            $("#reqErrorMsg").html("Login Account cannot be empty");
            $("#loginEmail").focus();
            return;
        }

        var loginPwd = $.trim($("#loginPwd").val());

        $.post('@Url.Action("Login","Home")', {
            loginID: loginEmail,
            loginPwd: loginPwd
        }, function (response) {
            response = JSON.parse(JSON.stringify(response));
            if (!response.IsValid)
                $("#reqErrorMsg").html(response.ErrorMessage);
            else
            {
                if ('@Model' != '')
                    window.location = '@Model';
                else
                    window.location = '@Url.Action("UserList", "User")';
            }
        });
    });
</script>

Code/MachineManagement/Views/Home/Menu.cshtml
<li class="mainHeaderMenu" style="margin-left: 380px;">
    <a class="dropButton" href='@Url.Action("UserList", "User")'>User List</a>
</li>
<li class="mainHeaderMenu">
    <a class="dropButton" href='@Url.Action("MachineList", "Machine")'>Machine List</a>
</li>